Emu/.emu_setup/core/gearsystem.sh
Emu/.emu_setup/core/genesis_plus_gx.sh
Emu/.emu_setup/core/picodrive.sh
Emu/.emu_setup/defaults/GG.opt
Emu/.emu_setup/defaults/MS.opt
Emu/GG/config.json
Emu/MS/config.json

The Gearsystem core uses a lot of CPU compared to both PicoDrive and Genesis Plus GX when emulating the Master System and Game Gear: from my testing, while operating under the smart CPU mode, Gearsystem runs at 1008MHz , whereas both Picodrive and Genesis Plus GX run at 480MHz. 
I've decided to change to Genesis Plus GX instead of Picodrive as it provides a good middleground between accuracy and performance.

Change default core for Game Gear/Master System to Genesis Plus GX

---

RetroArch/.retroarch/shaders/TV.glslp
RetroArch/.retroarch/shaders/blurry.glslp
RetroArch/.retroarch/shaders/gritty.glslp
RetroArch/.retroarch/shaders/medium.glslp
RetroArch/.retroarch/shaders/non-filtered.glslp
RetroArch/.retroarch/shaders/shaders/TV.glsl
RetroArch/.retroarch/shaders/shaders/gritty.glsl
RetroArch/.retroarch/shaders/shaders/quilez.glsl
RetroArch/.retroarch/shaders/shaders/sharp-bilinear-simple.glsl
RetroArch/.retroarch/shaders/shaders/stock.glsl
RetroArch/.retroarch/shaders/sharp.glslp

They work fine on my A30, full speed easily. They can resolve the nasty scaling when full screen (without resolution being an exact multiply). With these you can occupy all screen on gba, gb, gbc, gg, snes without nasty bad scaling artifacts.
Moved all presets to one folder for new users ease of life and readability

add simple light shaders, compatible to GLES 2.0

---

spruce/scripts/save_poweroff.sh

added very simple shutdown screen with spruce tree watermark to replace shutting the screen off before actual shutdown is complete. This is intended to reduce the chance of a user pulling out their SD card before the system is finished syncing the changes to  the SD card, which can lead to file corruption, especially of items in the spruce/settings folder.

Shutdown screen

---

spruce/scripts/enforceSmartCPU.sh
spruce/scripts/helperFunctions.sh
spruce/scripts/principal.sh
spruce/scripts/runtime.sh

The in-game menu built into ra32.miyoo will no longer have any control over the cpu speed or governor. This has been accomplished by only enabling write permissions to the cpu governor virtual file during one of the three set_<mode> helper functions.

Protect governor from miyoo

---

spruce/bin/Syncthing/syncthing_sync_check.sh

This causes the "Press Start to Cancel" text to appear off screen. 
I'm guessing this changed because when using the BG icon, we display text a bit differently

Get rid of empty new lines so text doesn't go off the screen

---

spruce/scripts/helperFunctions.sh

When wifi was being disabled in game, and then turned back on for the Syncthing check on Shutdown, the `check_and_connect` wifi function would always think it was connected, which led to failed Sync checks.
This is most likely due to the device still having an ip assigned to it but not verifying if we have an actual working connection.
This checks for a working connection which now correctly prompts a `Wait For Wifi Check` if Wifi was previously nuked.
Check for a working connection as well, not just an assigned IP

fix: ping connection to ensure its not a dead ip

---

Emu/.emu_setup/standard_launch.sh
spruce/bin/Syncthing/syncthingFunctions.sh
spruce/bin/Syncthing/syncthing_sync_check.sh
spruce/scripts/save_poweroff.sh

Before, `Syncthing Sync Check` did not work if you have `Disable Network Services in Game` or `Disable Wifi in Game`
The Sync would be skipped on RA Launch and would fail on RA Shutdown for a few reasons, but the TLDR is I wrote the checker with assumptions on startup/shutdown that aren't true anymore because of these new options.
* Run Sync Checker BEFORE we disable network services or wifi.
* Ensure we always start the Syncthing process if it isn't running when needed in `startup` and in `shutdown`

Syncthing  make sync check compatible with disabled network options

---

Emu/.emu_setup/core/fceumm.sh
Emu/.emu_setup/core/nestopia.sh
Emu/.emu_setup/core/quicknes.sh
Emu/.emu_setup/defaults/FC.opt
Emu/FC/config.json

Quicknes, a very, very fast NES emulation core that should be much easier on the A30's CPU and battery (it's about 3x faster than FCEUMM with fast forward testing). 4 games are broken due to lack of mapper support, which is documented [here](https://docs.libretro.com/library/fceumm/)

Expose quicknes core to UI

---

Emu/.emu_setup/standard_launch.sh
spruce/bin/Syncthing/syncthing_sync_check.sh
spruce/scripts/networkservices.sh

ST Sync Check was using long static sleeps and always assumed worse case scenario. This meant punishing everyone even if they kept their Wifi and Network services enabled in game.
Also due to how we kill network services in game, we sometimes put ST in a broken state when wifi/wlan would get killed before ST shuts down
* Ensure we kill network services in the foreground so ST exits gracefully and isn't put in a broken state due to a race condition with wifi/wlan
* Use polling mechanisms to ensure that script works for all types of possible toggles, such as `Disable Network Services in Game` and `Disable Wifi in Game`

ST Sync Check:  Make faster and more robust

---

multipass.cfg
spruce/scripts/wpa_watchdog.sh

Allows user to tell if network specified in multipass file is hidden by providing "1" value.
I added reading HIDDEN_1, HIDDEN_2 ...... from multipass and according to its value scan_ssid=1 is added in wpa_supplicant
According to https://wiki.archlinux.org/title/Wpa_supplicant#Connection if the network is hidden, wpa_supplicant should have scan_ssid=1.

feat(multipass): add marking hidden network in multipass

---

spruce/scripts/applySetting/retroArchRewind.sh

Due to performance issues, rewind should not be enabled for PSX when turned on via Advanced Settings:
When RetroArch rewind is turned on, for both `PCSX-ReARMed` and `SwanStation`:
- If rewind is not present in the core configuration, an override is added that disables rewind
- If rewind is present in the core configuration, it is updated to be disabled
When RetroArch rewind is turned off, for both `PCSX-ReARMed` and `SwanStation`:
- The `rewind_enable` entry in the configuration is removed

feat(ra): exclude PSX when enabling rewind in RetroArch

---

App/AdvancedSettings/readme.txt
miyoo/etc/group
miyoo/etc/passwd
spruce/bin/Samba/sambaFunctions.sh
spruce/scripts/applySetting/SAMBA.sh
spruce/scripts/applySetting/SSH.sh
spruce/scripts/runtime.sh

- adds `sprucegroup` group
- adds `spruce` user
Password generated using [mkpasswd](https://www.mkpasswd.net/index.php): user:pass = `spruce`:`happygaming`
other group and users come from existing `/etc/group` and `/etc/passwd` files - unsure which are required, but leaving them for now.

feat(ssh): allow ssh auth using spruce user

---

App/RandomGame/random.sh

`random.sh` was still attempting to use `$EMU_DIR/$EMU_NAME/launch.sh`, leading to an infinite loop. It now uses `.emu_setup/standard_launch.sh` instead.

fix(random): `random.sh` now uses `standard_launch.sh`

---

spruce/scripts/tasks/resetPPSSPP.sh
spruce/settings/settings_config

This pull adds a toggle to reset your PPSSPP configuration as an expert setting in Advanced Settings.
Reset is accomplished by overwriting the following files from `Emu/.emu_setup`:
- `/mnt/SDCARD/.config/ppsspp/PSP/SYSTEM/ppsspp.ini`
- `/mnt/SDCARD/.config/ppsspp/PSP/SYSTEM/controls.ini`

feat(ppsspp): add Reset PPSSPP configs to Advanced Settings

---

Updater/updater.sh
Updater/updaterFunctions.sh
spruce/scripts/helperFunctions.sh

It's still not perfect, but this PR at least restores basic OTA update capabilities for the flip.
- Fixes the `confirm()` function in `helperFunctions.sh`
- Adds the platform-specific key mappings from `helperFunctions.sh` into `updaterFunctions.sh`
- Backs up the `7zr` binary on 64-bit architectures before cleaning files. This enables the script to still use `7zr` to extract the new archive.

Flip OTA on flip

---

spruce/scripts/runtime.sh

There are times where this JSON file gets corrupted and causes all sorts of issues since it no longer becomes valid JSON.
Now what we do is we:
1. Checks if system.json contains valid JSON
2. If invalid, attempts to sanitize it (returns first valid JSON object/structure)
3. Falls back to the template if sanitization fails
4. Replaces the corrupted file with a clean version

Feat: Sanitize System JSON if it gets corrupted

---

.tmp_update/updater

Create a new dir in /sdcard/spruce/logs
Will likely move the PortMaster logs into their as well in a future commit

Log the output of runtime.sh to help debug any startup errors

---

Emu/PORT32/run_port.sh
Emu/PORT32/scan_for_segfault.sh

box86 does not seem to close when the app it is running segfaults
This means without terminal access you would have to hard reboot the device
To get around this start a script before launching that scans the log every 5s for a segfault, and if so kills box86

Scan for segfaults when running 32-bit ports

---

spruce/scripts/helperFunctions.sh

30 Seconds is sometimes slightly too short, ive had Wifi connect after 45 seconds due to a weak signal but it did connect! 
So I think 60 seconds is a fair and reasonable bump as it sucks to hit the timeout earlier especially knowing if I gave it a little more time it would connect

Wifi Timeout: Increase from 30 to 60 seconds

---

spruce/scripts/homebutton_watchdog.sh

Some ports don't have exit buttons or hotkeys (mainly older ones) so this allows exitting via long-press

Let long-press of the home button force kill ports

---

spruce/flip/recombine_large_files.sh
spruce/scripts/runtime.sh

Avoids hitting lfs limitations on github
Causes first boot to be longer (worthy trade off)

Go back to using split files instead of lfs

---

Emu/.emu_setup/standard_launch.sh

gptokeyb cannot run inside the chroot so we must run it outside of it
Fix tab vs spaces in portmaster part of standard_launch

Call gptokeyb from run_port for 32bit ports

---

spruce/scripts/runtime.sh

Should resolve later mounts not working due to being lost

Move the flip's overlay mount for 32bit support further up

---

spruce/scripts/bluetooth_watchdog.sh

We also do not need to remove /tmp/bluetooth_ready
It's deleted automatically

fix devices not connecting

---

App/PyUI/main-ui/controller/controller.py

If a long-render occurred, clear the input queue
Some of the long renders need to be fixed
Others are things like searching for roms which is expected
to take a few seconds when theres a lot on the card

Update PyUI to d23d8037a91e66f6aeca380f60d43395af71d4ce

---

App/BoxartScraper/scraper.sh

Fixed the Exit Image/Text being cut off on the flip
i don't own any other devices to check if their correct, I just set all planned supported devices to match the old setting

Boxart Scraper: Fix height of exit image/text on flip

---

spruce/scripts/helperFunctions.sh
spruce/scripts/runtime.sh
spruce/scripts/tasks/clearwifi.sh
spruce/scripts/wifi_watchdog.sh
spruce/scripts/wpa_watchdog.sh

Should clear up any reboot needed, and let us decide which platforms to have it enabled on (since existence of a file is true regardless of if on the a30 or flip)

Make WiFi checks based on platform, not existance of a file
