Roms/PORTS/2048.sh
Roms/PORTS/Anarch.sh
Roms/PORTS/CaveStory.sh
Roms/PORTS/Dinothawr.sh
Roms/PORTS/Mr. Boom.sh
Roms/PORTS/Pong.sh

ensure LR ports use hotkey profile without interfering with current spruce/REM mode controls

Ports hotkey fix

---

Emu/.emu_setup/core/puae.sh
Emu/.emu_setup/core/puae2021.sh
Emu/.emu_setup/core/uae4arm.sh
Emu/.emu_setup/defaults/AMIGA.opt
Emu/.emu_setup/defaults/ATARIST.opt
Emu/AMIGA/config.json
Emu/ATARIST/config.json

Changing the Amiga core should improve performance, this all may need testing. Addresses issue #107

Add Atari ST emu folder and change Amiga core to uae4arm

---

Emu/PICO8/import.sh
spruce/scripts/btnpwr.sh

pwr button long press to exit and import.sh only import cart game file

pico8 vibrate on exit when long press power button

---

spruce/scripts/gameswitcher_watchdog.sh
spruce/scripts/principal.sh
spruce/settings/spruce.cfg
spruce/settings/spruce_config

Add GS global toggle

---

spruce/bin/Syncthing/syncthing_sync_check.sh

Syncthing would be forever syncing or freeze if no folders were found but a device was connected.
Now we check for folders first and gracefully exit

fix: Syncthing check will now fail gracefully if no folders are configured

---

spruce/scripts/helperFunctions.sh

Fixes:
https://github.com/spruceUI/spruceOS/issues/336
Dang Carl

feat: add 30 second timeout to check_and_connect_wifi helper function

---

spruce/flip/home/.local/share/PortMaster/control.txt

Otherwise PM app will need to be opened to refresh it

Update default created control.txt in spruce/flip/home/.local/share/PortMaster/control.txt

---

App/PortMaster/jpg_to_png.py
App/PortMaster/launch.sh
App/PortMaster/update_images.sh

1) Support splash.png
2) Handle converting jpg to png
Conversion is handled via python script
Install Pillow for conversion

Better image handling for portmaster covers (JPG support and Splash)

---

App/PortMaster/launch.sh

We have some 32/armhf support so we should include them for now in the gui

Ensure when we launch PM that we overwrite what it thinks we support

---

Emu/.emu_setup/standard_launch.sh
spruce/flip/unbind-new-libmali.sh

Might revert and do it for JUST games using weston, but doing it for all for now
Unmount after port.
Also testing if we just want this on boot for flip vs just for ports

Use the new flip libmali for all portmaster games

---

spruce/scripts/principal.sh
spruce/scripts/runtime.sh

Only works for latest official firmware (miyoo355_fw_20250228)
If Gamma Loader was flashed earlier - official firmware should be reflashed.

Fix bluetooth for Flip

---

spruce/scripts/homebutton_watchdog.sh

It was causing weird lag / behavior of not actually unpausing

Remove pausing for non A30 devices in RA

---

spruce/scripts/homebutton_watchdog.sh
spruce/settings/platform/Flip.cfg

Key 3 is more than just the sticks, so the stick check must be longer

Don't ignore R2/L2 for homebutton watchdog

---

spruce/scripts/runtime.sh

Leaving commented as eventually we will want to fix the updater to support this

Do not mount over system libs as it breaks the spruce updater

---

spruce/scripts/networkservices.sh

runs under pid sftp-server and not sftpgo

fix sftpgo restarting constantly

---

App/PyUI/main-ui/OptionSelectUI.py
App/PyUI/main-ui/config.json

Example usage:
exit code 0 =user selected and cmd executed
exit code 1 = user hit b to cancel
```
export PYSDL2_DLL_PATH="/mnt/SDCARD/App/PyUI/dll"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/miyoo/lib"
killall -STOP MainUI
/mnt/sdcard/spruce/flip/bin/python3  /mnt/sdcard/App/PyUI/main-ui/OptionSelectUI.py "ListTitle" /mnt/sdcard/options.json
killall -CONT MainUI
```
Sample options file:  [options.json](https://github.com/user-attachments/files/20052379/options.json)

PyUI to 91700123b8c6768f9b4619b1f9e73e043b61432d

---

App/PyUI/config.json
App/PyUI/launch.sh
spruce/scripts/homebutton_watchdog.sh
spruce/scripts/principal.sh

Things are wonky if you launch PyUI over MainUI so make it a toggle instead

Toggle between MainUI and PyUI rather than launching PyUI over MainUI

---

spruce/scripts/homebutton_watchdog.sh

Also certain logs should probably not be verbose, unverbosed some of them
Also kill -9 if it doesnt shutdown from a kill -15

Only kill drastic and PPSSPP apps, not things with them in the launch args

---

App/PyUI/main-ui/MainUI.py
App/PyUI/main-ui/devices/bluetooth/bluetooth_scanner.py
App/PyUI/main-ui/devices/device.py
App/PyUI/main-ui/devices/miyoo/system_config.py
App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/devices/wifi/wifi_connection_quality_info.py
App/PyUI/main-ui/games/utils/rom_utils.py
App/PyUI/main-ui/menus/app/app_menu.py
App/PyUI/main-ui/menus/games/game_config_menu.py
App/PyUI/main-ui/menus/games/game_system_config.py
App/PyUI/main-ui/menus/games/game_system_select_menu.py
App/PyUI/main-ui/menus/games/roms_menu_common.py
App/PyUI/main-ui/menus/settings/bluetooth_menu.py
App/PyUI/main-ui/menus/settings/settings_menu.py
App/PyUI/main-ui/menus/settings/wifi_menu.py
App/PyUI/main-ui/run.sh
App/PyUI/main-ui/themes/theme.py
App/PyUI/main-ui/views/descriptive_list_view.py
App/PyUI/main-ui/views/grid_view.py
App/PyUI/main-ui/views/non_descriptive_list_view.py

Fixed
⚠️ Better determination of WiFi Signal
❌WifiMenu - controls
❌Battery icon always charging
❌Bluetooth Menu - Should remain in menu -- after pressed, toggling bt on will scan, press x to scan
❌Themes - Add defaults so they dont crash the system
❌Brightness setting is reset after reboot
❌Settings list jumping behavior if you go to bottom then up to volume and press left/right
❌Roms - Use Filter List for extensions
⚠Game Switcher
Unsure / Partial Fix?
Wifi - Needs more testing but mostly works. Seems to crash if you disable and then re-enable
Bluetooth Pairing Controllers?

Update PyUI to 2934feff124deb6d2704ff6fa444fa29da892e73

---

spruce/scripts/homebutton_watchdog.sh

Will need to figure out why kill -15 doesn't always work

Do not kill -9 RA

---

App/PyUI/main-ui/menus/games/game_system_select_menu.py
App/PyUI/main-ui/themes/theme.py

Fix icon for hopefully all systems (e.g. 32x)

Update to PyUI ffe11069e042c9d66a7e88b560e4c6b6cfea145a

---

App/PyUI/main-ui/controller/controller.py

Handle if the user continously holds an input

Update PyUI to 3d934b850c1bb9261f3013f7abff03dbedcba78a

---

App/PyUI/main-ui/controller/controller.py
App/PyUI/main-ui/devices/device.py
App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/display/display.py
App/PyUI/main-ui/menus/settings/settings_menu.py
App/PyUI/main-ui/views/grid_view.py
App/PyUI/main-ui/views/list_view.py

Try and load theme before saving a new setting to it Fix _map_system_brightness_to_miyoo_scale based on new values Adding some logging to try to detect wifi issues
Unload and reload bg texture when unloading or deloading display Reinit fonts on reinit display
Fix miyoo flip detection of charging
Render UI updates when waiting for user input

Update to PyUI f99f66e2c00b7420bb2ed16102a3e3d98cef3753

---

App/PyUI/main-ui/menus/settings/settings_menu.py

Do not show theme options where there is no config.json in the folder

Update to PyUI 4bfd76d3b0380f5eda0570321e2f672cdc7a5d73

---

App/PyUI/launch.sh
App/PyUI/main-ui/MainUI.py
App/PyUI/main-ui/controller/controller.py
App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/devices/utils/process_runner.py
App/PyUI/main-ui/devices/wifi/wifi_scanner.py
App/PyUI/main-ui/menus/settings/wifi_menu.py
App/PyUI/main-ui/utils/logger.py

Update PyUI to 06b6d02fbd0605a6601b4bca5946892a9eae1780

---

App/PyUI/main-ui/OptionSelectUI.py
App/PyUI/main-ui/devices/device.py
App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/menus/app/app_menu.py
App/PyUI/main-ui/menus/games/game_config_menu.py
App/PyUI/main-ui/menus/games/game_system_select_menu.py
App/PyUI/main-ui/menus/games/roms_menu_common.py
App/PyUI/main-ui/menus/main_menu.py
App/PyUI/main-ui/menus/settings/bluetooth_menu.py
App/PyUI/main-ui/menus/settings/settings_menu.py
App/PyUI/main-ui/menus/settings/wifi_menu.py
App/PyUI/main-ui/views/grid_view.py
App/PyUI/main-ui/views/list_view.py

Allow menus to adjust between list selections
i.e. fix volume not updating when in settings without exiting and re-entering

Update PyUI to b9de25637607e9a52d10a61bf0f84fbdbe9ca9c9

---

App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/devices/utils/process_runner.py
App/PyUI/main-ui/themes/theme.py

Monitor for a WiFi connection and restart as needed
If unable to connect even after multiple attempts then turn off wifi

Update PyUI to 2d08815b5b6401e099e163087a851b0213f207d2

---

App/PyUI/main-ui/devices/device.py
App/PyUI/main-ui/devices/miyoo/system_config.py
App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/menus/settings/settings_menu.py

Add support for contrast and saturation

Update PyUI to f43c7b9bbc876393ab77381d5499a37fbad3c76d

---

App/PyUI/main-ui/controller/controller.py
App/PyUI/main-ui/devices/bluetooth/bluetooth_scanner.py
App/PyUI/main-ui/devices/device.py
App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/display/display.py
App/PyUI/main-ui/games/utils/rom_utils.py
App/PyUI/main-ui/menus/games/game_select_menu.py
App/PyUI/main-ui/menus/games/roms_menu_common.py
App/PyUI/main-ui/menus/settings/bluetooth_menu.py

Taking a guess at adding HDMI support (don't have a cable)
Do not crash if a theme's background png is missing
More wifi logging
Only regenerate roms list on settings change
Switch from running cat to using open() for settings checks
Add hotplug support for bluetooth controllers
Only resolve the folder path once -- not once per game
Add basic pairing support for controllers

Update to PyUI 6d900bc18522b4dd9b07a1069a7775ce57cd64bd

---

App/PyUI/main-ui/devices/device.py
App/PyUI/main-ui/devices/miyoo/system_config.py
App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/menus/settings/settings_menu.py

Rename brightness to lumination and add brightness support
Fix WiFi status that broke as part of cat changes
Add more WiFi logging

Update PyUI to d0a65fa53278f19edc25e3f0b17f8b38e6e10d7a

---

App/PyUI/main-ui/display/display.py
App/PyUI/main-ui/menus/common/top_bar.py

Improve top bar height determination
Choose the largest height of all top bar elements,
not just the height of the bg

Update PyUI to 1c5546668c4ebe87c2076fbd80e7be8377e39d9e

---

App/PyUI/main-ui/MainUI.py
App/PyUI/main-ui/OptionSelectUI.py
App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/display/display.py
App/PyUI/main-ui/display/on_screen_keyboard.py
App/PyUI/main-ui/games/utils/game_system.py
App/PyUI/main-ui/games/utils/game_system_utils.py
App/PyUI/main-ui/menus/common/top_bar.py
App/PyUI/main-ui/menus/games/game_select_menu.py
App/PyUI/main-ui/menus/games/game_system_select_menu.py
App/PyUI/main-ui/menus/games/roms_menu_common.py
App/PyUI/main-ui/menus/games/searched_roms_menu.py
App/PyUI/main-ui/menus/games/utils/rom_select_options_builder.py
App/PyUI/main-ui/menus/main_menu.py
App/PyUI/main-ui/menus/settings/settings_menu.py
App/PyUI/main-ui/menus/settings/wifi_menu.py
App/PyUI/main-ui/option_select_test.sh
App/PyUI/main-ui/themes/theme.py
App/PyUI/main-ui/utils/logger.py
App/PyUI/main-ui/views/grid_view.py
App/PyUI/main-ui/views/list_view.py

Add a logger to OptionSelectUI
Fill out titles for usages of on screen keyboard, and no longer let it be optional
No longer crash if given an empty list to display
Add ability to put a message at the top of the on screen keyboard
Search for ROMS when pressing menu on the main home screen
Get the display names for systems from the game system config
In GridView have L/R move an entire page
Fix the menu selection bg not changing when a theme is changed without exiting settings
Ensure sound is working when launching a game or app
Get lumination from the config
Add some config options for better theme variety
Menu button is just barebones for testing. Will add an actual menu overlay with options

Update PyUI to 65fef1ef842062590e6548fc25f8443a3076774b

---

App/PyUI/main-ui/display/display.py
App/PyUI/main-ui/display/on_screen_keyboard.py
App/PyUI/main-ui/menus/games/pop_menu.py
App/PyUI/main-ui/menus/main_menu.py
App/PyUI/main-ui/themes/theme.py
App/PyUI/main-ui/views/list_view.py
App/PyUI/main-ui/views/text_list_view.py
App/PyUI/main-ui/views/view_creator.py

Start adding support for popup-menus
Add in basic rom search from the main menu only currently

Update PyUI to 4a88126c373838680e349488b02c7e25f211c930

---

App/PyUI/main-ui/menus/games/pop_menu.py
App/PyUI/main-ui/menus/main_menu.py
App/PyUI/main-ui/views/list_view.py
App/PyUI/main-ui/views/pop_text_list_view.py
App/PyUI/main-ui/views/view_creator.py
App/PyUI/main-ui/views/view_type.py

Do not render index text for popup menus
Refactoring to have popup menu go through the view creator

Update PyUI to 5bf0dbbe4a04c2f03d82e1d431e8114e92e7d38b

---

App/PyUI/main-ui/devices/miyoo/system_config.py

Fix reload_config() to actually reload the config

Update PyUI to fbeea32474f2ec97bcc7923c7fa9841ef890f257

---

App/PyUI/main-ui/MainUI.py
App/PyUI/main-ui/controller/controller.py
App/PyUI/main-ui/devices/bluetooth/bluetooth_scanner.py
App/PyUI/main-ui/devices/miyoo/miyoo_games_file_parser.py
App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/devices/utils/process_runner.py
App/PyUI/main-ui/devices/wifi/wifi_scanner.py
App/PyUI/main-ui/display/display.py
App/PyUI/main-ui/games/utils/game_system_utils.py
App/PyUI/main-ui/menus/games/game_system_select_menu.py
App/PyUI/main-ui/menus/games/game_system_select_menu_popup.py
App/PyUI/main-ui/menus/games/roms_menu_common.py
App/PyUI/main-ui/menus/settings/advance_settings_menu.py
App/PyUI/main-ui/menus/settings/bluetooth_menu.py
App/PyUI/main-ui/menus/settings/wifi_menu.py
App/PyUI/main-ui/themes/theme.py
App/PyUI/main-ui/utils/logger.py
App/PyUI/main-ui/utils/py_ui_config.py
App/PyUI/main-ui/views/image_list_view.py
App/PyUI/main-ui/views/list_view.py
App/PyUI/main-ui/views/non_descriptive_list_view.py
App/PyUI/main-ui/views/text_to_image_relationship.py
App/PyUI/main-ui/views/view_creator.py

Add a bunch of themeing options / improvements to the ROM select screen Use logger instead of print everywhere (now shows calling class/line#)

Update PyUI to b8df6ff370a25a988b7a931f3c575cfce6c29db2

---

App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/themes/theme.py
App/PyUI/main-ui/views/image_list_view.py

Add text scrolling on selected rom
configured via theme setting scrollRomSelectionText

Update PyUI to 8fd16fca02c8e9f99425fd6ed53f17f6c85e9494

---

App/PyUI/main-ui/devices/device.py
App/PyUI/main-ui/devices/miyoo/system_config.py
App/PyUI/main-ui/devices/miyoo_flip.py
App/PyUI/main-ui/display/display.py
App/PyUI/main-ui/display/on_screen_keyboard.py
App/PyUI/main-ui/menus/games/game_system_select_menu_popup.py
App/PyUI/main-ui/menus/games/search_games_for_system_menu.py
App/PyUI/main-ui/menus/games/searched_roms_menu.py
App/PyUI/main-ui/menus/main_menu.py
App/PyUI/main-ui/menus/main_menu_popup.py
App/PyUI/main-ui/menus/settings/basic_settings_menu.py
App/PyUI/main-ui/menus/settings/bluetooth_menu.py
App/PyUI/main-ui/menus/settings/settings_menu.py
App/PyUI/main-ui/menus/settings/wifi_menu.py
App/PyUI/main-ui/themes/theme.py
App/PyUI/main-ui/views/image_list_view.py
App/PyUI/main-ui/views/text_to_image_relationship.py
App/PyUI/main-ui/views/view_creator.py

Crop text in game selection screen so it doesnt run behind the boxart Add spacing to pad out shorter game names on scroll Increase the menu to draw at ~12FPS when idle
Miyoo treats lumination/brightness incorrectly, so we need to account for it Center boxart and fix scrolling text
Add all system game search as an option in the system select menu Allow pressing B to exit out of the on screen keyboard WPA passwords must be between 8 and 63 characters
Update scaling to be on the final canvas so all views should align 1:1

Update PyUI to b5624d1ccb068e9184f87a39263b76afa887b42e

---

App/PyUI/theme-overrides/PyUI/Themes/SPRUCE/config.json

Will not apply to SPRUCE-Simple

Disable recents in the SPRUCE theme

---

App/PyUI/main-ui/controller/controller.py
App/PyUI/main-ui/devices/miyoo/flip/miyoo_flip.py
App/PyUI/main-ui/devices/miyoo/trim_ui_joystick.py

Update main-ui.py to 6219970dcd970bc7257c682769780d5d83f284c0

---

App/PyUI/main-ui/menus/common/top_bar.py
App/PyUI/main-ui/menus/settings/basic_settings_menu.py

Display clock in menu bar
Will make it an option in the future

Update PyUI to 424cd7f58704551dde317b270166ebb09d391f18

---

App/PyUI/main-ui/menus/games/game_system_select_menu.py

Account for systems that do not have an icon in their theme or Emu folder

Update PyUI to 75e7dde37c27eff7dbe154d3d8f3da9767ed3ef6

---

App/PyUI/main-ui/apps/miyoo/miyoo_app_finder.py
App/PyUI/main-ui/controller/controller.py
App/PyUI/main-ui/devices/device.py
App/PyUI/main-ui/devices/device_common.py
App/PyUI/main-ui/devices/miyoo/flip/miyoo_flip.py
App/PyUI/main-ui/devices/miyoo/system_config.py
App/PyUI/main-ui/devices/trimui/trim_ui_brick.py
App/PyUI/main-ui/games/utils/game_system_utils.py
App/PyUI/main-ui/mainui.py
App/PyUI/main-ui/menus/app/app_menu.py
App/PyUI/main-ui/menus/common/top_bar.py
App/PyUI/main-ui/menus/games/game_system_config.py
App/PyUI/main-ui/menus/games/game_system_select_menu.py
App/PyUI/main-ui/menus/settings/basic_settings_menu.py
App/PyUI/main-ui/menus/settings/extra_settings_menu.py
App/PyUI/main-ui/menus/settings/theme/theme_selection_menu.py
App/PyUI/main-ui/themes/theme.py
App/PyUI/main-ui/themes/theme_patcher.py
App/PyUI/main-ui/views/grid_view.py

e525cb4 (HEAD -> master) Add support for stock brick 
0c1236d Hide analog stick calibration for the brick 
03f7112 WIP to get volume working on the brick
609147c Add sleep support for the brick
9bbed84 Add volume up/down key recognition for trimui brick 
b07f1fb A to select a new theme from a list, X to modify it 
0b08e39 Ensure caches cleared when init theme after 2nd time to support auto conversion 904d001 Basic theme scaling capabilities
aa70830 Have the settings menu prompt for power down instead of always power off 
1c51e58 amixer doesnt get the volume, stop having the log print errors from it
3d2df33 Prompt for power down instead of just powering off 
75adb32 Remove extra logging

Update PyUI to e525cb42923fb67642b5869092a98a8548f08032

---

App/PyUI/main-ui/menus/games/favorites_menu.py
App/PyUI/main-ui/menus/games/recents_menu.py
App/PyUI/main-ui/menus/games/utils/miyoo_game_list.py
App/PyUI/main-ui/menus/games/utils/rom_info.py
App/PyUI/main-ui/menus/games/utils/rom_select_options_builder.py
App/PyUI/main-ui/menus/games/utils/roms_list_manager.py

Miyoogameslist doesn't have extensions
Account for mapped names for recents/favorites
Do not remove ext from folder names. Folders do not have extensions Fix single line miyoogameslist.xmls

Update PyUI to 1043c50a2848a503dd45984498ef1386c3a04de6

---

App/PyUI/main-ui/menus/settings/basic_settings_menu.py

Make theme settings an obvious settings entry

Update PyUI to 2e1968a956aab9c37fd9a9cd667d5e957ced680d

---

App/PortMaster/launch.sh
App/PyUI/main-ui/devices/device.py
App/PyUI/main-ui/devices/miyoo/miyoo_device.py
App/PyUI/main-ui/devices/muos/muos_device.py
App/PyUI/main-ui/devices/trimui/trim_ui_device.py
App/PyUI/main-ui/games/utils/device_specific/miyoo_trim_game_system_utils.py
App/PyUI/main-ui/games/utils/device_specific/muos_game_system_utils.py
App/PyUI/main-ui/menus/games/file_based_game_system_config.py
App/PyUI/main-ui/menus/games/utils/rom_select_options_builder.py
Emu/PICO8/config.json
Emu/PORTS/config.json
spruce/scripts/firstboot.sh
spruce/scripts/homebutton_watchdog.sh

PyUI related updates
PICO8 only if bios files exist
PM folder moved on first boot (vs copied on app launch)
Use PyUI menu for ports

Misc Updates pyUI/pico8/ports

---

App/PyUI/main-ui/themes/theme.py

Include default font for when a theme is missing a font

Update PyUI to c909ec6e5aee948384bc6e2af9dff507b357023b

---

Themes/SPRUCE/config.json

Tree icon is in the left most spot

Add offset for clock to spruce theme by default

---

App/PyUI/main-ui/menus/settings/wifi_menu.py
spruce/scripts/wpa_watchdog.sh

Update PyUI to a57608951524a77e5bd0a920b0cbb0b91a9d0ab3

Have PyUI handle multi network natively

---

App/PyUI/main-ui/devices/miyoo_trim_common.py
App/PyUI/main-ui/games/utils/device_specific/miyoo_trim_game_system_utils.py
App/PyUI/main-ui/games/utils/device_specific/muos_game_system_utils.py
App/PyUI/main-ui/games/utils/game_system.py
App/PyUI/main-ui/games/utils/rom_utils.py

Update PyUI to a6a2777b3088fb663ca2bb772cda5657df9101ba

Attempt to add support for multi sd card on the flip w/ PyUI

---

App/PyUI/main-ui/devices/miyoo_trim_common.py
App/PyUI/main-ui/games/utils/device_specific/miyoo_trim_game_system_utils.py
App/PyUI/main-ui/views/carousel_view.py

Hopefully fix carousel view and multi sd card setups

Carousel View / Multi SD

---

spruce/settings/platform/Flip.cfg

This reverts commit 60d22753d810192fddaeaa6b18c19ef9206a9801.

Revert "flip: correct wpa_supplicant.conf path"

---

App/PyUI/main-ui/menus/games/favorites_menu.py
App/PyUI/main-ui/menus/games/file_based_game_system_config.py
App/PyUI/main-ui/menus/games/game_select_menu_popup.py
App/PyUI/main-ui/menus/games/in_game_menu_listener.py
App/PyUI/main-ui/menus/games/muos_game_system_config.py
App/PyUI/main-ui/menus/games/retroarch_in_game_menu_popup.py
App/PyUI/main-ui/menus/games/roms_menu_common.py
App/PyUI/main-ui/menus/games/utils/favorites_manager.py
App/PyUI/main-ui/menus/games/utils/roms_list_manager.py

Update to PyUI 8655585a39cadf0b3555278f315051451b43ec19

Add option to sort favorites alphabetically

---

App/PyUI/main-ui/devices/device_common.py
App/PyUI/main-ui/devices/miyoo/flip/miyoo_a30.py
App/PyUI/main-ui/devices/miyoo/flip/miyoo_flip.py
App/PyUI/main-ui/devices/miyoo/miyoo_device.py
App/PyUI/main-ui/devices/miyoo/trim_ui_joystick.py
App/PyUI/main-ui/devices/miyoo_trim_common.py
App/PyUI/main-ui/display/display.py
App/PyUI/main-ui/mainui.py
App/PyUI/main-ui/menus/games/in_game_menu_listener.py
App/PyUI/main-ui/menus/games/utils/daijisho_theme_index.py
App/PyUI/main-ui/themes/theme_patcher.py

PyUI 22fb1652a3ef33034183bc0fc8a0a287dbaec13f

Update PyUI to version with Miyoo A30 support

---

App/PyUI/main-ui/devices/miyoo/flip/miyoo_a30.py
App/PyUI/main-ui/devices/miyoo/flip/miyoo_flip.py
App/PyUI/main-ui/devices/miyoo/miyoo_device.py
App/PyUI/main-ui/devices/miyoo_trim_common.py
App/PyUI/main-ui/devices/trimui/trim_ui_device.py

PyUI version 41120672e3254dce2cfa75f30fac7dc97340b7be

Fix Miyoo A30 wifi on PyUI

---

App/PyUI/lang/English.json
App/PyUI/lang/Español.json
App/PyUI/main-ui/devices/miyoo/flip/miyoo_flip.py
App/PyUI/main-ui/devices/trimui/trim_ui_device.py
App/PyUI/main-ui/mainui.py
App/PyUI/main-ui/menus/language/language.py
App/PyUI/main-ui/menus/main_menu.py
App/PyUI/main-ui/menus/settings/extra_settings_menu.py
App/PyUI/main-ui/menus/settings/language_menu.py
App/PyUI/main-ui/utils/py_ui_config.py

Update to PyUI 219655c0e5ea7ac903e69c232206610122a5eff3

Language support started / fix app launching on brick
